### ISSUE TITLE
Refactor Arrow/Board components

### ISSUE THREAD

**Issue by Kregopaulgue** [what-the-hub/vue-game#20]
Details:
Refactor ```Arrow``` and ```Board``` components, so that:
1. Their inputs/outputs (props/emitted events) are crystal clear
2. It is possible to understand the flow of data in the components
3. ```Arrow``` components creation doesn't require creating the first one manually

**Comment by what-the-hub** [comment]
@Kregopaulgue I propose to discuss this issue at the meeting and possibly close this issue

**Comment by what-the-hub** [comment]
we discussed the necessity of this issue with @Kregopaulgue. It is no longer needed
