### ISSUE TITLE
Crete PR template

### ISSUE THREAD

**Issue by silchencko** [what-the-hub/vue-game#21]
**Description:**

As **an engineer**, I **want** to have a default PR template. So I can use it each time I create a PR to simplify its creation.

**Refs:**

- [docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

**Acceptance criteria:**

- template should be located in `/.github/PULL_REQUEST_TEMPLATE.md`

Template:
**Refs:**

`issue_link`

**Proposed Changes:**

- `Add a description here`

**Screenshots:**

`Add screenshots here`

**Comment by what-the-hub** [comment]
@silchencko can i put the template in a folder `docs`? It will looks like `docs/.github/PULL_REQUEST_TEMPLATE.md`
I think it will not be superfluous
